### PR TITLE
Remove dependency on pinned version of concat and update tests

### PR DESCRIPTION
**Pull request by throwaway99**

### CODE REVIEW

**Comment by alexmuller** [comment]
Thanks for opening this pull request! I'm a bit nervous about removing the upper bound of the dependency entirely - that means that if there was a breaking change in version 3 of the concat module it could break for users of this module.

Could you still achieve what you need to by setting `{ "name": "puppetlabs/concat", "version_requirement": ">=1.0.0 <2.0.0" }` in the module metadata? You could then either leave 1.2.1 in the fixtures file or bump it to 1.2.5.

Thanks again for opening this.

**Comment by trevorrea** [comment]
Hi Alex,

Yes that is a much better suggestion. Code review in action :)

I'll fix

Thanks.

**Comment by throwaway99** [comment]
Hi Alex,

Yes that's much better suggestion. Code review in action :) I'll update in a bit.

Thanks.

**Comment by throwaway99** [comment]
Sorry - forgot to say that I had updated with your suggestions. Please review.  Thanks.

**Comment by alexmuller** [comment]
Sorry to take such a long time to review this and thanks again for opening this pull request - I've merged it into master as 9533c5575909565d8eb31d0e122f4084f8a664aa.

**Pull request closed without merging**
